apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # Init container to create a custom index.html
      initContainers:
        - name: init-index
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /usr/share/nginx/html
              echo "<h1>Welcome to RK!</h1>" > /usr/share/nginx/html/index.html
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
