apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rollingupdate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-rolling
    spec:
      initContainers:
        - name: init-index
          image: busybox
          command:
            - sh
            - -c
            - echo "<h1>Welcome to RK1 RollingUpdate - $(POD_NAME)</h1>" > /usr/share/nginx/html/index.html
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rollingupdate-svc
spec:
  type: NodePort
  selector:
    app: nginx-rolling
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
