apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-nginx-time
spec:
  schedule: "*/1 * * * *"   # every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: updater
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  PODS=$(kubectl get pods -l app=nginx-time -o jsonpath='{.items[*].metadata.name}')
                  for pod in $PODS; do
                    kubectl exec $pod -- sh -c "echo '<h1>Welcome to RK - $(date)</h1>' > /usr/share/nginx/html/index.html"
                  done
          restartPolicy: OnFailure
