apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-time
  template:
    metadata:
      labels:
        app: nginx-time
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          emptyDir: {}
